redis: &redis
  adapter: redis
  url: <%= Rails.env.production? ? ENV['REDISTOGO_URL'] : 'redis://localhost:6379/1' %> 


production: *redis
development:
  adapter: async
test:
  adapter: <%= ENV['TEST_FRAMEWORK'] == 'rspec' ? 'test' : 'async'  %>
